### ISSUE TITLE
Only allows one partial per file

### ISSUE THREAD

**Issue by beefchimi** [markadrake/node-simple-html-includes#1]
Seems like you can only have a single `partial` per file?

**index.html**
```
@Html.Partial("./src/views/partials/_test-partial.html", {
    "myVariable": "myVal"
});

@Html.Partial("./src/views/partials/_new-partial.html", {
    "myVariable": "HELLO IT ME"
})
```

Only the first `Partial` gets parsed and added to the output.

`dependencies: [ './src/views/partials/_test-partial.html' ]`

**Comment by markadrake** [comment]
@beefchimi thanks and I'm sorry it took a few months for me to acknowledge your issue. If you're still using the package, please take a look at the latest version 0.1.7 - it may resolve this very issue. 

It also resolves an issue - only the first property in the json was being updated. 

I'll be adding more tests in the upcoming days - specifically one to test for this case. I'll wait for you to respond, or I write the test, before closing this issue.

Thank you!

**Comment by beefchimi** [comment]
No worries dude - I can't even remember what project I was using this for 😆 

Cheers!
