### ISSUE TITLE
Set partials path prefix/suffix

### ISSUE THREAD

**Issue by beefchimi** [markadrake/node-simple-html-includes#2]
Would be great if I could optional define these when calling `node-simple-html-includes`. Rather than:

`@Html.Partial("./path/to/partial.html", ...`

If I could just:

`@Html.Partial("partial", ...`

**Comment by markadrake** [comment]
I agree! Perhaps I could check the package.config file for some variable or setting? Any suggestion or feedback about how to best implement this?
